name: Test Deploy

on:
  push:
    branches: ["main", "preLive", "dev"] # we can add more branches if needed such as "preLive", "dev"

jobs:
  deploy:
    runs-om: ubuntu-latest
    steps:
      - name: Doing a deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: /
            cd /var/www/
            git pull
